<?php namespace boxxy;
require_once('autoload.php');
require_once('interfaces/app.php');
require_once('interfaces/container.php');
require_once('interfaces/request.php');
require_once('interfaces/resolver.php');
require_once('interfaces/factory.php');
require_once('interfaces/view.php');
require_once('classes/di.php');
require_once('classes/app.php');
require_once('classes/container.php');
require_once('classes/mapper_pdo.php');
require_once('classes/controller.php');
require_once('classes/request.php');
require_once('classes/resolver.php');
require_once('classes/view.php');
require_once('Pimple.php');